### ISSUE TITLE
Data Set unavailability

### ISSUE THREAD

**Issue by DevRSC** [CharlesGaydon/Dater-to-Vec#2]
Good day, Mr. Charles

I tried to replicate the process of creating a recommendation engine, but I stumbled upon a problem. The dataset on occamslab.com is unavailable since the website domain is now for sale.
![image](https://user-images.githubusercontent.com/108634205/204293634-c483e0d2-aae3-4981-844a-1830875cac1c.png)

If by any chance do you have a copy of the dataset?

**Comment by ifkid** [comment]
> Good day, Mr. Charles
> 
> I tried to replicate the process of creating a recommendation engine, but I stumbled upon a problem. The dataset on occamslab.com is unavailable since the website domain is now for sale. ![image](https://user-images.githubusercontent.com/108634205/204293634-c483e0d2-aae3-4981-844a-1830875cac1c.png)
> 
> If by any chance do you have a copy of the dataset?



[download here](https://github.com/tolleiv/thesis/blob/master/Datasets/libimseti-complete.zip  )  

Hope that helps
